jwt:
  secret:
    key: your-base64-encoded-secret-key

spring:
  application:
    name: coffee-project

  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:3306/coffee_db
    username: your-username
    password: your-password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none  # 예시 설정, 로컬 개발 환경에서는 update 또는 create 사용 가능
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  data:
    # Redis 설정
    redis:
      host: localhost
      port: 6379

    # 페이징 설정
    web:
      pageable:
        max-page-size: 100

  # Kafka 설정
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: coffee-order-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "kr.spartaclub.coffeeproject"
        spring.json.use.type.headers: false
        spring.json.value.default.type: "kr.spartaclub.coffeeproject.domain.order.event.OrderCompletedEvent"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# 서버 상태 모니터링 (/actuator/health)
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
