jwt:
  secret:
    key: your-base64-encoded-secret-key

spring:
  application:
    name: coffee-project

  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:3306/coffee_db
    username: your-username
    password: your-password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none  # 예시 설정, 로컬 개발 환경에서는 update 또는 create 사용 가능
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  data:
    # Redis 설정
    redis:
      host: localhost
      port: 6379

    # 페이징 설정
    web:
      pageable:
        max-page-size: 100

# 서버 상태 모니터링 (/actuator/health)
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
