jwt:
  secret:
    key: your-base64-encoded-secret-key

spring:
  application:
    name: coffee-project

  datasource:
    url: jdbc:mysql://localhost:3306/coffee_db
    username: your-username
    password: your-password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none  # 개발 시 update 사용 가능
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  #  Redis 설정
  data:
    redis:
      host: localhost
      port: 6379
